/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name varchar,
    date_of_birth date,
    escape_attempts int,
    neutered boolean,
    weight_kg decimal
);

ALTER TABLE animals
  ADD species text;

CREATE TABLE owners (id int GENERATED ALWAYS AS IDENTITY, full_name text, age int, PRIMARY KEY(id));

CREATE TABLE species (id int GENERATED ALWAYS AS IDENTITY, name text, PRIMARY KEY(id));

ALTER TABLE animals ADD COLUMN id SERIAL PRIMARY KEY;

ALTER TABLE animals 
DROP COLUMN species;

ALTER TABLE animals
  ADD species_id int;

ALTER TABLE animals
ADD FOREIGN KEY (species_id) REFERENCES species (id);

ALTER TABLE animals
  ADD owner_id int;

ALTER TABLE animals
ADD FOREIGN KEY (owner_id) REFERENCES owners (id);

CREATE TABLE vets (
   id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
   name VARCHAR(30) NOT NULL,
   age int NOT NULL,
   date_of_graduation DATE NOT NULL
);

CREATE TABLE specializations (
   vet_id INT,
   species_id INT ,
   FOREIGN KEY (vet_id) REFERENCES vets(id),
   FOREIGN KEY (species_id) REFERENCES species(id)
);

CREATE TABLE visits (
   animal_id INT,
   vet_id INT ,
   date_of_visit DATE, 
   FOREIGN KEY (animal_id) REFERENCES animals(id),
   FOREIGN KEY (vet_id) REFERENCES vetS(id)
);

-- Add an email column to the owners table
ALTER TABLE owners ADD COLUMN email VARCHAR(120);

-- Create index
CREATE INDEX animal_id_asc ON visits(animal_id ASC);

CREATE INDEX vet_id_desc ON visits(vet_id DESC);

CREATE INDEX email_asc ON owners(email ASC);

